### ISSUE TITLE
Question: limits based on plans? 

### ISSUE THREAD

**Issue by markudevelop** [aldeed/meteor-plans#1]
Hey Aldeed 

Thanks for sharing the package, I was wondering if you ever needed to introduce limits based on plan for example free plan can add 5 rss feeds while pro plan has limit of 15 rss feeds.

If you did how did you organise it? Extend the plan object with extra function checks? I'm having manual checks at the methods for now. Love to get some ideas maybe there is a package for it? Couldn't find any.

Thank you

**Comment by aldeed** [comment]
This package only handles figuring out what plan the user is on based on outside subscriptions. Not the limit or feature switch logic. So yes, you should be doing your own check in the method, checking if `AppPlans.has('pro')` when they try to add a feed and their feed count is already 5 or more.
